
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const run = () => {
    // Corrected Path: From /scripts/ to /public/product-images
    const imagesDir = path.join(__dirname, '../public/product-images');
    const outputFile = path.join(__dirname, '../src/utils/imageMap.ts');

    console.log(`Scanning images in: ${imagesDir}`);

    if (!fs.existsSync(imagesDir)) {
        console.error(`ERROR: Image directory not found at ${imagesDir}`);
        return;
    }

    try {
        const files = fs.readdirSync(imagesDir).filter(f => !f.startsWith('.'));
        console.log(`Found ${files.length} images.`);

        const content = `// This file is auto-generated by scripts/update_image_map.js
// It contains the list of all available product images and a helper to match SKUs.

const AVAILABLE_IMAGES = ${JSON.stringify(files, null, 4)};

const PROJECT_URL = 'https://luekeyeoxoymchguhrdt.supabase.co';
const BUCKET = 'product-images';

/**
 * Attempts to resolve a product image path based on the SKU.
 * @param sku The product SKU (e.g., "0227NZ-010-L")
 * @returns The Supabase Storage URL, or undefined if no match found.
 */
export const resolveProductImage = (sku: string): string | undefined => {
    if (!sku) return undefined;

    // Normalize SKU for comparison
    const normalizedSku = sku.toUpperCase();

    const matchedImage = AVAILABLE_IMAGES.find(filename => {
        // Remove extension to get the "base name"
        const baseName = filename.substring(0, filename.lastIndexOf('.')).toUpperCase();

        // Check if SKU starts with this base name
        // e.g. "0227NZ-010-L" starts with "0227NZ-010"
        // Also ensuring it's a prefix match with boundary or exact match
        if (normalizedSku === baseName || normalizedSku.startsWith(baseName + '-')) {
            return true;
        }
        return false;
    });

    if (matchedImage) {
        // Return Supabase Storage URL
        // Encode the filename to handle spaces/symbols
        return \`\${PROJECT_URL}/storage/v1/object/public/\${BUCKET}/\${encodeURIComponent(matchedImage)}\`;
    }

    return undefined;
};
`;

        fs.writeFileSync(outputFile, content);
        console.log("Updated src/utils/imageMap.ts");

    } catch (err) {
        console.error("Error updating image map:", err);
    }
};

run();
